fnam = input("May I have your first name, please? ")
lnam = input("May I have your last name, please? ")
print("Thank you.")
print("\nYour name is " + fnam + " " + lnam + ".")
student_name=input("please tell us your name,please?")
admission_number=input("tell us what is your admission number please")
print("thankyou")
print("\n","your details are",student_name+","+admission_number)
print("+" + 10 * "-" + "+")
print(("|" + " " * 10 + "|\n") * 5, end="")
print("+" + 10 * "-" + "+")
